### ISSUE TITLE
Large volume creation queue can starve PV requests

### ISSUE THREAD

**Issue by sureshvis** [NetApp/trident#73] opened 2017-12-21 19:24 UTC
Step 1 : created a PVC (name: test1) with 5 MB, trident warned with below error

Error creating volume. API status: failed, Reason: Size “5MB” (“5242880B”) is too small. Minimum size is “20MB” (“20971520B”).

Step 2: deleted the PVC which was warning from step 1

Step 3: created new PVC with 1GB request (with new PV name: test2), the trident would not create new PV but keep trying to create PV  from step 1 in loop.

when the PVC was deleted, the corresponding object from trident is not getting cleared

**Comment by kangarlou** [comment] 2017-12-21 19:54
Assuming you meant PVC (not PV) in steps 1, 2, and 3, I went through the steps and didn't encounter any problem. As long as the PVC with the request for a 5MB volume (test1) is around, Trident periodically tries creating a PV for it. Creation of a new PVC (test2), whether after deletion of test1 or before, should proceed with no problem.

As a Trident user, you should only create and delete PVCs, not PVs, when the reclaim policy is set to `Delete`.

**Comment by sureshvis** [comment] 2017-12-21 20:00
sorry, yes  i meant PVC. 

The PVC is deleted, i still see trident trying to create the PV.

**Comment by kangarlou** [comment] 2017-12-21 21:12
More information about this issue: Suresh and I confirmed that HOL blocking is not an issue with Stateful Sets at low scale. In Suresh's case, he was creating a Stateful Set with 500 replicas. Because PVCs were requesting for volumes smaller than 20MB, dynamic provisioning was failing for the 500 PVCs. It appeared because Trident reattempts provisioning for the 500 PVCs every 60 seconds, the backlog for Trident was getting longer and longer to the extent that some valid provisioning requests were getting starved. To address this issue, we should evaluate and improve Trident's scalability during failed provisioning.

**Comment by gnarl** [comment] 2020-05-21 20:29
Closing this issue as we haven't had another customer report this issue recently. We also have functional scale tests that create 100 PVCs in our CI.

**Closed by gnarl** 2020-05-21 20:29 UTC
Labels: bug, tracked
