### ISSUE TITLE
trident-csi ServiceAccount label k8s_version fails if reported k8s version has special characters

### ISSUE THREAD

**Issue by dgabrysch** [NetApp/trident#417] opened 2020-06-29 12:19 UTC
https://github.com/NetApp/trident/blob/bc1f5ee3c9b12c46b6dd65ab6b94a4e210db3781/operator/controllers/provisioner/installer/installer.go#L1710

We tried to deploy the trident-operator but it fails and cannot create the trident-csi ServiceAccount. When "pre-creating" the ServiceAccount with e.g.  k8s_version: v1.17.1 it does not match and the Operator deletes the ServiceAccount.

This is the error message:
time="2020-06-29T11:45:02Z" level=debug msg="Object not created, waiting." err="ServiceAccount \"trident-csi\" is invalid: metadata.labels: Invalid value: \"v1.17.1+912792b\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" increment=7.845938145s yamlDocument="---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: trident-csi\n  labels:\n    trident_version: v20.04\n    app: controller.csi.trident.netapp.io\n    k8s_version: v1.17.1+912792b\n  ownerReferences:\n  - kind: TridentProvisioner\n    name: trident\n    uid: 32a83406-b9c3-4d02-8384-052b2aab78bc\n    apiVersion: trident.netapp.io/v1\n    controller: true\n"
time="2020-06-29T11:45:10Z" level=debug msg="Parsed YAML into unstructured object." group= kind=ServiceAccount version=v1
time="2020-06-29T11:45:10Z" level=debug msg="Found API resource." group= kind=ServiceAccount resource=serviceaccounts version=v1
time="2020-06-29T11:45:10Z" level=debug msg="Creating object." kind=ServiceAccount name=trident-csi namespace=trident
time="2020-06-29T11:45:10Z" level=error msg="Object creation failed." err="ServiceAccount \"trident-csi\" is invalid: metadata.labels: Invalid value: \"v1.17.1+912792b\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" yamlDocument="---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: trident-csi\n  labels:\n    trident_version: v20.04\n    app: controller.csi.trident.netapp.io\n    k8s_version: v1.17.1+912792b\n  ownerReferences:\n  - kind: TridentProvisioner\n    name: trident\n    uid: 32a83406-b9c3-4d02-8384-052b2aab78bc\n    apiVersion: trident.netapp.io/v1\n    controller: true\n"

Our APIServer reports: v1.17.1+912792b as its' version so we cannot deploy because of this issue.

Kind regards,
dgabrysch

**Comment by gnarl** [comment] 2020-06-29 14:03
This is a duplicate of an [existing issue](https://github.com/NetApp/trident/issues/399). A fix will be included with the Trident 20.07 release. You can still successfully install Trident by using the tridentctl install method.

**Closed by gnarl** 2020-06-29 14:03 UTC
