### ISSUE TITLE
Support CSI Dynamic Volume Limits

### ISSUE THREAD

**Issue by jiuchen1986** [NetApp/trident#361] opened 2020-03-23 19:17 UTC
**Describe the solution you'd like**
We'd like Trident could support the "Dynamic volume limits" feature described in https://kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits. In that case, more flexibility is brought as the limit number of total volumes could be controlled at Trident level.
And of cause, the feature implementation should include how to configure the limit from Trident side.

**Describe alternatives you've considered**
No alternatives are available when it comes to Trident, especially when use "ontap-nas-economy" type of backend and SVM sharing between multiple Kubernetes clusters.

**Additional context**
None

**Comment by adkerr** [comment] 2020-03-23 19:22
That feature simply limits how many volumes can be attached to a single Kubernetes node at a time, not how many total volumes could be created by Trident.

**Comment by gnarl** [comment] 2022-09-20 17:51
Closing this issue as a duplicate of Issue #622.

**Closed by gnarl** 2022-09-20 17:51 UTC
Labels: enhancement
