### ISSUE TITLE
image netapp/trident-operator:21.07.0 is not available on docker hub

### ISSUE THREAD

**Issue by khassel** [NetApp/trident#616] opened 2021-08-09 11:41 UTC
The above image seems to be removed from docker hub, so latest release `v21.07.0` is not installable.

```bash
skopeo inspect docker://netapp/trident-operator
{
    "Name": "docker.io/netapp/trident-operator",
    "Digest": "sha256:ca29e75bcfdc6811e4ef29386510a27b8af9bd6f9ac9e6ad97ed68e446f9efed",
    "RepoTags": [
        "20.04.0",
        "20.04",
        "20.07.0",
        "20.07.1",
        "20.07",
        "20.10.0",
        "20.10.1",
        "20.10",
        "21.01.0",
        "21.01.1",
        "21.01.2",
        "21.01",
        "21.04.0",
        "21.04.1",
        "21.04",
        "latest"
    ],
    "Created": "2021-06-21T19:12:25.261157349Z",
    "DockerVersion": "19.03.12",
    "Labels": {
        "app": "trident-operator.netapp.io",
        "description": "Trident Operator",
        "maintainers": "The NetApp Trident Team"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:5dea5ec2316d4a067b946b15c3c4f140b4f2ad607e73e9bc41b673ee5ebb99a3",
        "sha256:fa81a9eede656ae9eff6d9066d1f3b4c05c808234d9d6dc5e2db8e8bb239ca46"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
        "BIN=trident-operator",
        "K8S="
    ]
}
```

**Comment by obassett** [comment] 2021-08-09 11:49
There was a message on slack,  Basically the 21.07 image has been pulled for now.

"We decided to pull the v21.07.0 release, on account of an issue identified with the snapshotReserve parameter. This could potentially make CSI VolumeSnapshots unusable and can be avoided by setting snapshotReserve value to zero.
The issue is being addressed and will be fixed with the v21.07.1 release. The inconvenience caused is regretted. Users are encouraged to post on the channel and ask their questions with regards to this. We are here to help"

**Comment by balaramesh** [comment] 2021-08-09 13:40
@khassel v21.07.0 has been pulled temporarily from the Trident repo. This was done to address issue #611. v21.07.1 will be available in a few days time and will contain the fix

**Comment by khassel** [comment] 2021-08-09 19:28
Thanks for the info's, will wait for patch release.

**Comment by gnarl** [comment] 2021-08-12 19:26
Trident 21.07.1 has been released.

**Closed by gnarl** 2021-08-12 19:26 UTC
Labels: bug
