### ISSUE TITLE
trident allows deletion of volumes in use

### ISSUE THREAD

**Issue by equinox0815** [NetApp/trident#20] opened 2017-04-18 14:06 UTC
Hi,

Volumes that are created by trident via the kubernetes API (using a PVC) can be deleted using the REST API although the PVC is still there and in use. Pods who use the volume loose access to the store and all data is lost. I don't think this is a good default. Are there any plans to change this or is this inentional?

regards
 christian

**Comment by kangarlou** [comment] 2017-04-18 14:33
Hi. Trident's REST API is meant to be used by storage/IT admins only. In that sense, deleting a volume using Trident's REST API is no different than deleting a volume through a storage system's UI. The scenario you described can also happen if an admin inadvertently or intentionally deletes a volume on the storage backend while the PVC, or more generally the volume for non-Kubernetes cases, is still in use. As you can imagine, better coordination between an admin and a user is the only way to prevent such problems from happening.

**Comment by adkerr** [comment] 2017-04-18 14:40
Would it be possible to detect that it's in use and require a force flag or something similar in that situation to help prevent irreversible accidents?

**Comment by cdragga** [comment] 2017-04-18 14:51
In Kubernetes 1.6, at least, there's no way to definitively check if a PVC is in use.  Thus, that's not really possible.

**Comment by equinox0815** [comment] 2017-04-18 14:55
hmmmm your right @cdragga... even kubectl doesn't keep me from deleting a PVC which is in use...

**Comment by adkerr** [comment] 2017-04-18 14:55
I think we only map the volumes, at least in ONTAP and ESeries, at mount time. Could we use that to determine useage status?

**Comment by adkerr** [comment] 2017-04-18 15:02
I am getting mixed up with ndvp's workflow. Trident maps on create as we are not tied into the kubernetes mount action.

**Comment by equinox0815** [comment] 2017-04-18 15:05
@kangarlou sure deleting volumes in the storage system's UI is always possible and you would end up with the same result. But of course it's much more obvious for the admins that deleting volumes in the back end can be potentially catastrophic. The storage system doesn't know about the automatic provisioning after all.
Trident on the other hand is well aware of that fact and as a user of the trident API it's not what i would expect from it. That's why i think it is so problematic.

**Comment by kangarlou** [comment] 2017-04-18 17:27
> The storage system doesn't know about the automatic provisioning after all. Trident on the other hand is well aware of that fact and as a user of the trident API it's not what i would expect from it.

Trident is aware of provisioning but is currently not aware of activities on a provisioned volume as it's not a volume plugin. More specifically, Trident doesn't know if a volume is mounted or not or by whom. As discussed earlier in this thread, one can delete a PVC from underneath a running pod and there are no safeguards in Kubernetes to prevent that. Ideally, both Kubernetes and Trident should track relationships between pods and PVCs and disallow deletion of active PVCs/volumes.  

The main reason you can delete volumes provisioned for Kubernetes deployments through Trident's REST API is to recover from failures. By the virtue of being an external provisioner, it's possible that a user successfully deletes a PVC while the deletion of the volume fails on the backend (say due to network outage). To force deletion of such volumes once the problem is remedied, one has to use Trident's REST API to delete the volume from the storage backend and from Trident's etcd datastore.

**Comment by korenaren** [comment] 2017-06-13 20:15
Closing based on @kangarlou last comment. Not a bug.

**Closed by korenaren** 2017-06-13 20:15 UTC
Labels: bug, tracked
