### ISSUE TITLE
Failed to resize ReadWriteMany volume online

### ISSUE THREAD

**Issue by mac-chaffee** [NetApp/trident#793] opened 2023-01-04 16:45 UTC
**Describe the bug**
After resizing a ReadWriteMany volume that was mounted by two different pods on two different nodes, I got the following errors:

Kubelet:
```
Jan 04 10:30:44 k8s-node01.k8s.renci.org kubelet[5323]: E0104 10:30:44.712926    5323 operation_generator.go:2033] 
  NodeExpandVolume.NodeExpandVolume failed for volume "pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b" (UniqueName: "kubernetes.io/csi/csi.trident.netapp.io^pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b") pod "apsviz-geoserver-dev-geoserver-c5d5bd785-7hm7s" (UID: "9deeddf8-4bfd-4acd-a0f9-d386a2d90d36") : 
  Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = device  to expand is not attached
Jan 04 10:30:44 k8s-node01.k8s.renci.org kubelet[5323]: E0104 10:30:44.712994    5323 nestedpendingoperations.go:335] 
  Operation for "{volumeName:kubernetes.io/csi/csi.trident.netapp.io^pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b podName: nodeName:}" failed. No retries permitted until 2023-01-04 10:32:46.71296456 -0500 EST m=+1701421.587760292 (durationBeforeRetry 2m2s). Error: NodeExpandVolume.NodeExpandVolume failed for volume "pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b" (UniqueName: "kubernetes.io/csi/csi.trident.netapp.io^pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b") pod "apsviz-geoserver-dev-geoserver-c5d5bd785-7hm7s" (UID: "9deeddf8-4bfd-4acd-a0f9-d386a2d90d36") : 
  Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = device  to expand is not attached
```

Trident:
```
time="2023-01-04T15:26:40Z" level=info msg="Received something other than the expected stagingTargetPath." 
requestID=636f3c0a-b7b1-4a79-8131-db48ad98a66b requestSource=CSI stagingTargetPath=/var/lib/kubelet/plugins/kubernetes.io/csi/csi.trident.netapp.io/773aa903155a058b71574d0fbef2a62fba17322aef5684c1677d2d7c9dc524cd/globalmount volumeId=pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b volumePath="/var/lib/kubelet/pods/9deeddf8-4bfd-4acd-a0f9-d386a2d90d36/volumes/kubernetes.io~csi/pvc-adaa39c9-43fa-46bd-a94e-17c2252a747b/mount"
```

This error repeats every 2 min or so. The PVC and the PV both display the new size as if the resize was successful, but the error repeats. Stopping and restarting both containers (thus causing the volume to be unmounted from both nodes) cleared the error.

**Environment**

- Trident version: 21.10.1
- Trident installation flags used: 
- Container runtime: containerd v1.6.8
- Kubernetes version: 1.24.4
- Kubernetes orchestrator: Kubespray
- Kubernetes enabled feature gates: 
- OS: RHEL8
- NetApp backend types: ONTAP 9.8P5 NAS

**To Reproduce**
1. Create a RWM PVC and two pods that each mount the volume:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mypvc0
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: alpine:latest
    command: [ "sleep", "99999" ]
    volumeMounts:
      - name: test
        mountPath: /tmp
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: mypvc0
---
apiVersion: v1
kind: Pod
metadata:
  name: debug2
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: alpine:latest
    command: [ "sleep", "99999" ]
    volumeMounts:
      - name: test
        mountPath: /tmp
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: mypvc0
```
2. Ensure the pods spawn on two different nodes
3. `kubectl edit pvc mypvc0` and change the size from 1Gi to 2Gi
4. Wait a few minutes. Observe `kubectl get events` shows a `VolumeResizeFailed` event

**Expected behavior**
The volume should be resized without warnings and without requiring pod restarts.

**Comment by gnarl** [comment] 2023-02-13 14:44
Hi @mac-chaffee,

For an ontap-nas-* volume this should work as the Trident controller will send a request to ONTAP to expand the storage volume. A volume attachment isn't needed for this operation but in your log snippets Kubelet and the Trident Node Plugin are being called to expand the volume.

Please provide additional relevant logs or you can open a support case with NetApp support to collect all of the logs needed and we can then determine where the issue is.

**Comment by gnarl** [comment] 2023-02-21 22:47
Closing this issue as a response hasn't been received from the OP.

**Closed by gnarl** 2023-02-21 22:47 UTC
Labels: bug
