### ISSUE TITLE
Trident-csi pods from DaemonSet remains in Terminating after kubernetes version upgrade

### ISSUE THREAD

**Issue by andreivnst** [NetApp/trident#581] opened 2021-05-27 10:55 UTC
**Describe the bug**
One or more trident-csi pods controlled by trident-csi DaemonSet remains in Terminating state after kubernetes version upgrade. As a root cause, the kubernetes upgrade determines a trident-csi-token-xxxx Secret to be renewed, secret that is mounted as a volume in the pods. The DaemonSet senses secret recreation and forces pods recreation. Some of them are deleted but one/more remains in Terminating, forcing the Trident app to not work properly (DaemonSet cannot recreate the new pods untill all pods  are deleted). As a workaround you have to forcefully delete all the Terminating pods with --force and --grace-period=0 flags at kubectl CLI command

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.01.0
- Trident installation flags used:
imageRegistry: ...
operatorDebug: true
operatorImage: ...
tridentDebug: true
tridentAutosupportImage: ...
tridentLogFormat: "json"
tridentImage: ...
- Container runtime: 19.03.13
- Kubernetes version: upgrade from v1.19.2-rancher1-1 -> v1.20.6-rancher1-1
- Kubernetes orchestrator: Rancher v2.5.8
- Kubernetes enabled feature gates: -
- OS: CentOS 7.8.2003 

**To Reproduce**
Upgrade kubernetes version on usercluster or recreate trident-csi-token-xxxx

**Expected behavior**
Pods successfully deletes and DaemonSet recreates the new ones that uses the new token

**Additional context**

kubectl get all -n trident
NAME                                    READY   STATUS        RESTARTS   AGE
pod/trident-csi-6f6859b7c8-w8dhv        6/6     Running       0          9m6s
pod/trident-csi-jz449                              0/2     Terminating   0          50d
pod/trident-operator-57cd9dc747-twhbh   1/1     Running       0          50d

Events from Terminating pod:

Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  6m38s                 kubelet  MountVolume.SetUp failed for volume "certs" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  6m38s                 kubelet  MountVolume.SetUp failed for volume "trident-csi-token-d4dqm" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  4m36s                 kubelet  Unable to attach or mount volumes: unmounted volumes=[trident-csi-token-d4dqm], unattached volumes=[trident-tracking-dir plugins-mount-dir sys-dir host-dir registration-dir plugin-dir dev-dir certs trident-csi-token-d4dqm pods-mount-dir]: timed out waiting for the condition
  Normal   Killing      4m36s                 kubelet  Stopping container trident-main
  Normal   Killing      4m36s                 kubelet  Stopping container driver-registrar
  Warning  FailedMount  26s (x10 over 6m37s)  kubelet  MountVolume.SetUp failed for volume "trident-csi-token-d4dqm" : secret "trident-csi-token-d4dqm" not found

The new token as a secret:
kubectl get secrets -n trident | grep trident-csi
trident                       trident-csi                                               Opaque                                7      9m36s
trident                       trident-csi-token-l9vlq                                   kubernetes.io/service-account-token   3      9m36s

**Comment by ntap-arorar** [comment] 2021-05-27 14:40
Hello @andreivnst 

Thanks for reporting this issue, the reason we wait for the existing pod to delete before re-creating once is due to #487. I have not encountered this issue of the old pod stuck in a terminating state forever so would appreciate it if you can share some more information:

1. If this happened as a result of just the Kubernetes version upgrade?
2. Less likely, but are you aware of the process running on those terminating pods that may be blocking the pod from terminating? Usually, logs from the container would indicate the same.
3. After the force deletion of the pod, when the daemonset pods came up online were they able to properly mount the volumes on that node? 
4. Also what backend do you have (e.g. ontap-san, ontap-nas, Solidfire etc.) ?

Thank you!

**Comment by andreivnst** [comment] 2021-05-28 12:27
Hello,

1. Yes, the situation appeared after Kubernetes version upgrade and encountered it on all my managed Kubernetes clusters (~12)
2. I tried debugging the situation but the containers seemed to be stopped. (somehow just the pod remained hanging). The logs didn't seem to offer much information regarding this issue.
3. Yes, after the forcefully deletion of the pods, the new pods came back online and mounted the volumes.
4. ontap-nas on some clusters and ontap-nas-economy on others (depends on the stage prod/dev)

Thank you

**Comment by roycec** [comment] 2021-06-09 12:00
Same here during upgrade from Kubernetes 1.18.4 to 1.20.6, also Trident 21.01.01. The terminating pods had to be removed forcefully, then everything worked again.

**Comment by balaramesh** [comment] 2021-06-29 15:03
@roycec @andreivnst I attempted the same with Trident v21.04.1 on a kubeadm cluster and found the upgrade to go through without any issues. I had deployed Trident with the operator and the logs indicate that it identified a Kubrenetes version change:

time="2021-06-28T20:22:59Z" level=debug msg="Initialized Kubernetes API client." cli=kubectl flavor=k8s namespace=default timeout=30s version=v1.19.0
time="2021-06-28T20:22:59Z" level=debug msg="Initialized installer." namespace=default
time="2021-06-28T20:22:59Z" level=info msg="CR updated." CR=trident CRD=TridentOrchestrator
time="2021-06-28T20:22:59Z" level=info msg="A Trident deployment was found by label." deployment=trident-csi namespace=default
W0628 20:22:59.164262       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-06-28T20:22:59Z" level=debug msg="Alpha snapshot CRD not present." CRD=volumesnapshots.snapshot.storage.k8s.io
W0628 20:22:59.186186       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-06-28T20:22:59Z" level=debug msg="Alpha snapshot CRD not present." CRD=volumesnapshotclasses.snapshot.storage.k8s.io
W0628 20:22:59.191343       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
time="2021-06-28T20:22:59Z" level=debug msg="Alpha snapshot CRD not present." CRD=volumesnapshotcontents.snapshot.storage.k8s.io
time="2021-06-28T20:22:59Z" level=debug msg="Kubernetes version is supported." version=v1.19.0
time="2021-06-28T20:22:59Z" level=info msg="Kubernetes version has changed; Trident operator should change the Trident installation as per the new Kubernetes version" currentTridentConfigK8sVersion=1.18 newK8sVersion=1.19

I am still not sure if this was a bug fixed with v21.04.1 or if it is reproducable with v21.01.1. I will give that a try next

**Comment by ntap-arorar** [comment] 2021-11-17 05:00
@andreivnst

We were able to reproduce this issue and this time we had the environment to understand what may have caused this issue.

Our understanding is that during K8s upgrade:
1. Trident Operator re-creates the service account (and K8s subsequently creates a new service account token)
2. CSI on a given node tries to perform certain operations (I guess unstage or unpublish) on that node using the previous service account token, which is not present anymore, thus causing it to fail and maybe preventing the pod from completely deleting.
3. Some nodes are able to do this depending on when the service account token was refreshed, so there is definitely some race condition here.

A potential solution here is that the Operator should not delete/re-create the service account during K8s upgrade, this step is not required for Service Account and is a source of this issue.

**Comment by gnarl** [comment] 2022-01-25 15:43
This issue is fixed with [commit 8b65103](https://github.com/NetApp/trident/commit/8b6510387895986e47bfc04e06c43f38c34d2c47) and will be included in the Trident 22.01 release.

**Closed by gnarl** 2022-01-25 15:43 UTC
Labels: bug, tracked
