### ISSUE TITLE
Volume Snapshot READYTOUSE False

### ISSUE THREAD

**Issue by garrotemar** [NetApp/trident#419] opened 2020-07-13 23:40 UTC
Bug Description
I'm try to create a Volume Snapshot from a NFS Volume and the state to volume snapshot in not ready.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.04
- Trident installation flags used:  standard
- Container runtime: cri-o
- Kubernetes version: v1.17.1
- Kubernetes orchestrator: Openshift 4.4
- Kubernetes enabled feature gates: 
- OS: CoreOS 4.4
- NetApp backend types: ONTAP 9

I have crated a PV
NAME                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistent-volume-claim-nas   Bound     pvc-9d59662f-fa69-4e63-bf09-18b460f8c069   1Gi        RWO            nfssilver      3d4h

I'm try to create a snapshot from this volume with volume snapshot
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: pvc1-snap
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: persistent-volume-claim-nas

The results is:
NAME        READYTOUSE   SOURCEPVC                     SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
pvc1-snap   false        persistent-volume-claim-nas                                         csi-snapclass   snapcontent-3320ec04-e13f-45f0-b1e8-5bcf13dda629                  24h

Ready to Use is False and not use for a clone to a new PV.

**Expected behavior**
I'm expected that the volumen snapshot is ready to use for clone to a new PV.

**Comment by balaramesh** [comment] 2021-01-25 16:32
@garrotemar were you able to get to the bottom of that issue? I have encountered this before and in my case, it was caused by the external snapshot-controller not running. I was able to fix it by deploying the snapshot-controller using the manifest found [here](https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/snapshot-controller)

**Comment by gnarl** [comment] 2021-01-28 17:44
Closing this issue as there isn't a response from OP indicating that this is still a problem.

**Closed by gnarl** 2021-01-28 17:44 UTC
Labels: bug, tracked
