### ISSUE TITLE
In case of trident's PV lose, Is it possible to recreate the Trident's PV ?

### ISSUE THREAD

**Issue by roldancer** [NetApp/trident#206] opened 2019-01-12 17:43 UTC
Hi, In case of Trident's PV lose, would it be interesting to have the option for Trident etcd's PV recreation from an existing backend/Storage Class/PV's provisioned previusly, let suppose the following case:

1) Trident is Up&Running in K8S cluster named XX.
2) For any reason, the Trident etcd's PV is lose or corrupted.
3) It would be interesting to rebuild/redeploy the Trident in this way:
     a) ./tridentctl uninstall -n trident
     b) ./tridentctl install -n trident --from-existing-storageclass (This parameter should load the existing NetApp's Storage class and PV provisioned)
     c) ./tridentctl -n trident create backend -f setup/backend.json
    
Would be it possible to have this feature/parameter "--from-existing-storageclass" ?

By the way, when Kubernetes's CRD will be supported ?

Many thanks.

**Comment by kangarlou** [comment] 2019-01-13 21:32
Hi. In case, you accidentally delete the PVC and PV used by Trident's etcd, you can reinstall Trident using the same volume that you used previously to install Trident and access the old etcd data. This is because volume creation in Trident is an idempotent operation, so as long as the name of the new etcd volume matches the name of the old volume (see `tridentctl install --volume-name`), you should recover the preexisting data.

It's on our roadmap to support CRDs for various use cases. What particular use case are you referring to here? Thanks!

**Comment by redbaron** [comment] 2019-01-29 08:02
@kangarlou , I am also interested in this. Question is to how to rebuild state from k8s into new empty etcd in case  original was lost (not just PV, but whole data)

**Comment by kangarlou** [comment] 2019-01-29 15:04
@redbaron Backing up etcd (either by using `etcdctl snapshot save` or by backing up the etcd volume) is currently the only way to preserve the Trident state. Importing existing PVCs/PVs/volumes is on the Trident roadmap.

**Comment by innergy** [comment] 2019-01-30 22:17
Duplicate of #74

**Closed by innergy** 2019-01-30 22:17 UTC
