### ISSUE TITLE
Unable to create PVC from snapshot if G is used as size instead of Gi

### ISSUE THREAD

**Issue by manosoft** [NetApp/trident#617] opened 2021-08-11 07:55 UTC
**Describe the bug**
I want to clone my existing application for test purpose.
I'm following below 
1. Create snapshot of existing PVC
2. Create PVC from snapshots
3. Start clone application using PVC from step 2

At step 2, I see below error and PVC creation fails.
failed to provision volume with StorageClass "ntap-trident": error getting handle for DataSource Type VolumeSnapshot by Name snap001: requested volume size 1000000000 is less than the size 1000001536 for the source snapshot snap001

**Original PVC Snippet:**
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
```

**Snippet PVC from Snapshot:**
```
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: snap001
  resources:
    requests:
      storage: 1G
  storageClassName: ntap-trident
  volumeMode: Filesystem
```

In both cases, size is same 1G, still PVC creation fails with **requested volume size 1000000000 is less than the size 1000001536 for the source snapshot snap001**

**Environment**
- Trident version: 21.04.0
- Trident installation flags used: No custom flags used.
- Container runtime: Docker 1.13.1
- Kubernetes version: v1.18.20
- Kubernetes orchestrator: Vanilla Kubernetes
- Kubernetes enabled feature gates: NA
- OS: CentOS Linux release 7.7.1908
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
Run below commands using attached yamls.
Please edit 01-pvc-create.yaml 03-snapshot.yaml 04-pvc-from-snapshot.yaml files with appropriate storageclass and volumesnapshotclass.

kubectl create -f 00-create-namespace.yaml
kubectl create -f 01-pvc-create.yaml
kubectl create -f 02-pod-create.yam
kubectl create -f 03-snapshot.yaml
kubectl create -f 04-pvc-from-snapshot.yaml
kubectl create -f 05-pod-clone.yaml

**Expected behavior**
We should be able to create PVC from Volume Snapshot.

**Additional context**
[00-create-namespace.yaml.txt](https://github.com/NetApp/trident/files/6966689/00-create-namespace.yaml.txt)
[01-pvc-create.yaml.txt](https://github.com/NetApp/trident/files/6966696/01-pvc-create.yaml.txt)
[02-pod-create.yaml.txt](https://github.com/NetApp/trident/files/6966697/02-pod-create.yaml.txt)
[03-snapshot.yaml.txt](https://github.com/NetApp/trident/files/6966692/03-snapshot.yaml.txt)
[04-pvc-from-snapshot.yaml.txt](https://github.com/NetApp/trident/files/6966694/04-pvc-from-snapshot.yaml.txt)
[05-pod-clone.yaml.txt](https://github.com/NetApp/trident/files/6966695/05-pod-clone.yaml.txt)

**Comment by manosoft** [comment] 2021-08-11 09:01
1G translates to 976562.5Ki, but volumesnapshot size is shown as 964Ki, hence the difference of 1536bytes it seems

```[root@snap-verification]# k get volumesnapshot  -nsnap-test
NAME      READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snap001   true         my-pvc                              976564Ki      ntap-snap       snapcontent-9f196783-4125-485d-8f51-d38bc7db99f5   89m            89m
```

**Comment by gnarl** [comment] 2021-08-16 14:14
Hi @manosoft,

Even though you are creating a clone in your steps to reproduce this issue this is a duplicate of #550. The cloning workflow creates a snapshot which is then used to create the new PV. We are currently investigating how to best fix this issue.

Thanks for the providing additional information on this issue.

**Closed by gnarl** 2021-08-16 14:14 UTC
Labels: bug
