### ISSUE TITLE
Add Trident to OperatorHub.io

### ISSUE THREAD

**Issue by nickcmaynard** [NetApp/trident#432] opened 2020-08-11 15:24 UTC
What plans are there for adding Trident to [OperatorHub.io](https://operatorhub.io/)?

**Comment by gnarl** [comment] 2020-08-11 17:01
Hi @nickcmaynard, 

I'm closing this as it is a duplicate of [issue #425](https://github.com/NetApp/trident/issues/425).

**Closed by gnarl** 2020-08-11 17:01 UTC

**Comment by ntap-arorar** [comment] 2020-08-11 17:12
As part of each reconcile loop Operator sets status as well as event message in accordance with the current state of Trident.

There is a logic in place to not to update the CR status if it is same as old status (to avoid continuous CR update loops). However, event messages are set each and every time thus resulting in the above behaviour and increment of the age counter. 

This behaviour is benign but can cause confusion, to avoid this confusion operator should only update the event message if the status is actually getting changed, else not.
