### ISSUE TITLE
Trident deployment fail - toomanyrequests: You have reached your pull rate limit

### ISSUE THREAD

**Issue by fperillo76** [NetApp/trident#618] opened 2021-08-11 12:37 UTC
Hello team, I assume the question I'm going to ask has been raised many times already. I tried to search for answers but I did not get the right help so far. By the way I and my team (@Andrea Tosato) are struggling to deploy Trident on a Racher environment. We run into the "pull rate limit" error and, although we made a lot of troubleshooting, we did not find the way to solve the issue. I would really appreciate an help from someone who ran into the same problem.I'm going to give you further info about what we made to troubleshoot the error:

1. we created a docker user;
2. we applied the "Pull an Image from a Private Registry" -> https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
3. we read through the blog https://netapp.io/2021/05/21/docker-rate-limit-issue/ even if this was RedHat related and we tried to apply the same stuff with no success;

Lastly I'm attaching the output of the error we got once we try to run the Trident installation.
I would be pleasure to get an help.
Many thanks in advance.

[error installing trident.txt](https://github.com/NetApp/trident/files/6968391/error.installing.trident.txt)

**Comment by scaleoutsean** [comment] 2021-08-13 12:22
Duplicate of https://github.com/NetApp/trident/issues/515

**Comment by gnarl** [comment] 2021-08-16 16:56
Closing this issue as a duplicate of #515.

**Closed by gnarl** 2021-08-16 16:56 UTC
