### ISSUE TITLE
ability to specify nodename or nodeselector during tridentctl install

### ISSUE THREAD

**Issue by beth2016** [NetApp/trident#265] opened 2019-08-07 20:11 UTC
we have a k8s cluster with worker nodes of diff arch (x86, s390x, win),  Since trident only works on x86, it fails to install if it happens to land on a non x86 node,   how can we specify nodeselector or nodename during tridentctl install? thanks

**Comment by korenaren** [comment] 2019-08-19 14:38
Thanks @beth2016 . this looks like a duplicate of #264 so we will track it there.

**Closed by korenaren** 2019-08-19 14:38 UTC
