### ISSUE TITLE
trident install error on openshfit 3.9 

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#156] opened 2018-07-25 18:53 UTC
hi 

i am installing trident 1.8.04 on openshift 3.9 with kubernetes 1.9 . Trident install failing at bound stage.

INFO Deleted PV.                                   pv=trident
FATA Install failed; PVC trident was not bound after 120000000000 seconds 

any idea what could be the issue ?

**Comment by kapilarora** [comment] 2018-07-30 10:31
two possibilities:
1) you haev a default storage class
Work around: temporarily remove the default storage class for the installation

2) You have pending PVCs and they are stealing the trident PV
Workaround: ensure no PVCs are in pending state during install

**Comment by acsulli** [comment] 2018-07-30 13:40
Closing this one, it was a duplicate of #120 and was [answered there](https://github.com/NetApp/trident/issues/120#issuecomment-408434420).

**Closed by acsulli** 2018-07-30 13:40 UTC
