### ISSUE TITLE
air gaped(offline)method of trident not working with operator in k8

### ISSUE THREAD

**Issue by eselvam** [NetApp/trident#724] opened 2022-05-12 05:57 UTC
we are using air gaped method to install the trident.  we pulled the image to our local artifactory. 

we changed the file: tridentorchestrator_cr.yaml to mention our local registry and imagepull secret however the trident operator is not picking up to spin the 6 pods for netapp trident.

apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imageRegistry: example.com:443/idev
  tridentImage: example.com:443/dev/trident:22.01.1
  imagePullSecrets:
  - name: local-registry
error:
EBU[2022-05-12T06:50:39+01:00] Trident pod not yet running, waiting.         increment=552.330144ms status="trident pod is not running"
DEBU[2022-05-12T06:50:40+01:00] Trident pod not yet running, waiting.         increment=1.080381816s status="trident pod is not running"
DEBU[2022-05-12T06:50:41+01:00] Trident pod not yet running, waiting.         increment=1.31013006s status="trident pod is not running"
DEBU[2022-05-12T06:50:42+01:00] Trident pod not yet running, waiting.         increment=1.582392691s status="trident pod is not running"
DEBU[2022-05-12T06:50:44+01:00] Trident pod not yet running, waiting.         increment=2.340488664s status="trident pod is not running"
DEBU[2022-05-12T06:50:46+01:00] Trident pod not yet running, waiting.         increment=4.506218855s status="trident pod is not running"
DEBU[2022-05-12T06:50:51+01:00] Trident pod not yet running, waiting.         increment=3.221479586s status="trident pod is not running"
DEBU[2022-05-12T06:50:54+01:00] Trident pod not yet running, waiting.         increment=5.608623477s status="trident pod is not running"
DEBU[2022-05-12T06:51:00+01:00] Trident pod not yet running, waiting.         increment=7.649837917s status="trident pod is not running"
DEBU[2022-05-12T06:51:07+01:00] Trident pod not yet running, waiting.         increment=15.394871241s status="trident pod is not running"
DEBU[2022-05-12T06:51:23+01:00] Trident pod not yet running, waiting.         increment=29.271137938s status="trident pod is not running"
DEBU[2022-05-12T06:51:52+01:00] Trident pod not yet running, waiting.         increment=56.813324746s status="trident pod is not running"
DEBU[2022-05-12T06:52:49+01:00] Trident pod not yet running, waiting.         increment=42.855832355s status="trident pod is not running"

Please help us to fix it. Thanks.

**Comment by eselvam** [comment] 2022-05-12 05:58
still the operator looking for external image not local:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m59s                  default-scheduler  Successfully assigned trident/trident-csi-76cdccb5f6-pclmd to eu-mirantp-w002.iconcr.com
  Warning  Failed     5m52s                  kubelet            Failed to pull image "netapp/trident:22.01.1": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/05/0539933c511f5a74943616f0d5a2aac201d2927e49bd5fec15e6d6c42ab0cb91/data?verify=1652337676-ZyjFhvqdD0tDvNEY728GKYErgOY%3D: dial tcp 104.18.125.25:443: i/o timeout
  Warning  Failed     5m4s                   kubelet            Failed to pull image "netapp/trident-autosupport:22.01": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/11/1156a97fc13942e01a942af656244d0a83025daf719da80197e208f7c570c38d/data?verify=1652337724-BZXW8bWdpuy4w9lSk7gohaWxcEo%3D: dial tcp 104.18.121.25:443: i/o timeout
  Warning  Failed     4m16s                  kubelet            Error: ErrImagePull
  Normal   Pulling    4m16s                  kubelet            Pulling image "k8s.gcr.io/sig-storage/csi-attacher:v3.4.0"
  Warning  Failed     3m46s                  kubelet            Failed to pull image "k8s.gcr.io/sig-storage/csi-attacher:v3.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     3m46s                  kubelet            Error: ErrImagePull
  Normal   Pulling    3m46s                  kubelet            Pulling image "k8s.gcr.io/sig-storage/csi-resizer:v1.3.0"
  Warning  Failed     2m58s                  kubelet            Error: ErrImagePull
  Warning  Failed     2m58s                  kubelet            Failed to pull image "k8s.gcr.io/sig-storage/csi-resizer:v1.3.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Pulling    2m58s                  kubelet            Pulling image "k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3"
  Warning  Failed     2m28s                  kubelet            Failed to pull image "k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Pulling    2m28s (x2 over 6m58s)  kubelet            Pulling image "netapp/trident:22.01.1"
  Warning  Failed     2m28s                  kubelet            Error: ErrImagePull
  Normal   Pulling    82s (x2 over 5m52s)    kubelet            Pulling image "netapp/trident-autosupport:22.01"
  Warning  Failed     82s (x2 over 5m52s)    kubelet            Error: ErrImagePull
  Warning  Failed     82s                    kubelet            Failed to pull image "netapp/trident:22.01.1": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/05/0539933c511f5a74943616f0d5a2aac201d2927e49bd5fec15e6d6c42ab0cb91/data?verify=1652337946-O3Ix%2FWAb6kCAPGQ1Q9cGLlFTWmk%3D: dial tcp 104.18.124.25:443: i/o timeout
  Normal   Pulling    34s (x2 over 5m4s)     kubelet            Pulling image "k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0"
  Warning  Failed     34s (x2 over 5m4s)     kubelet            Error: ErrImagePull
  Warning  Failed     34s                    kubelet            Failed to pull image "netapp/trident-autosupport:22.01": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/11/1156a97fc13942e01a942af656244d0a83025daf719da80197e208f7c570c38d/data?verify=1652337994-BV2d2VRPKOHYI5exWm8x7QJjwKo%3D: dial tcp 104.18.124.25:443: i/o timeout
  Warning  Failed     19s (x2 over 4m16s)    kubelet            Failed to pull image "k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by ntap-arorar** [comment] 2022-05-12 19:55
@eselvam Operator logs might provide some more clues. If this `tridentorchestrator_cr.yaml` is properly formatted, then I would check to see if there is any other `TridentOrchestrator` CR that might exist and is in use for deploying Trident. You will need to run `kubectl get torc` command.

**Comment by eselvam** [comment] 2022-05-14 05:56
Thanks. Here is my tridentorchestrator_cr.yaml. is the below file is correct? Could you please check and help me here.

 cat tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident  namespace: trident
spec:
  debug: true
  imageRegistry: myprivateregistry:443/repo
  tridentImage: myprivateregistry:443/repo/imagename
  imagePullSecrets:
  - name:myregistrykey

    On Friday, May 13, 2022, 01:25:46 AM GMT+5:30, Rohit Arora ***@***.***> wrote:  
 
 


@eselvam Operator logs might provide some more clues. If this tridentorchestrator_cr.yaml is properly formatted, then I would check to see if there is any other TridentOrchestrator CR that might exist and is in use for deploying Trident. You will need to run kubectl get torc command.

**Comment by eselvam** [comment] 2022-05-17 04:48
Here is the operator log. No useful information on it.  Shall you please help me here. I am using latest trident.

W0517 04:46:10.504292       1 reflector.go:442] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: watch of *v1.TridentOrchestrator ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.spec.imagePullSecrets of type string") has prevented the request from succeeding
W0517 04:46:11.487347       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
E0517 04:46:11.487390       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.TridentOrchestrator: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
W0517 04:46:13.116908       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
E0517 04:46:13.116946       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.TridentOrchestrator: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
W0517 04:46:19.358186       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
E0517 04:46:19.358272       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.TridentOrchestrator: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
W0517 04:46:29.345170       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string
E0517 04:46:29.345211       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.TridentOrchestrator: failed to list *v1.TridentOrchestrator: json: cannot unmarshal object into Go struct field TridentOrchestratorSpec.items.spec.imagePullSecrets of type string

The operator running fine:

 kubectl get all -n trident
NAME                                   READY   STATUS    RESTARTS   AGE
pod/trident-operator-9b7586b46-sfvzn   1/1     Running   0          6m2s

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/trident-operator   1/1     1            1           6m3s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/trident-operator-9b7586b46   1         1         1       6m3s

**Comment by ntap-arorar** [comment] 2022-05-17 05:48
@eselvam It seems the issue is with the `imagePullSecrets` value. Here is an example: https://github.com/NetApp/trident/blob/master/deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml. There is no need to append `name`.

Can you please try and see if it resolves the issue?

**Comment by eselvam** [comment] 2022-05-17 07:57
Thanks.  I changed it and now it is problem with image pull back off issue. Let me check and get back to you. Thanks.

    On Tuesday, May 17, 2022, 11:18:39 AM GMT+5:30, Rohit Arora ***@***.***> wrote:  
 
 


@eselvam It seems the issue is with the imagePullSecrets value. Here is an example: https://github.com/NetApp/trident/blob/master/deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml. There is no need to append name.

Can you please try and see if it resolves the issue?

**Comment by ntap-arorar** [comment] 2022-05-17 16:14
@eselvam I am glad you are past that issue.

**Comment by mdekoster** [comment] 2022-07-22 08:21
Hi,

I seems the operator creates the `trident-csi` deployment that contains the following images:

k8s.gcr.io/sig-storage/csi-attacher
k8s.gcr.io/sig-storage/csi-provisioner
k8s.gcr.io/sig-storage/csi-resizer
k8s.gcr.io/sig-storage/csi-snapshotter

In an air gapped cluster the `k8s.gcr.io` repository cannot be reached. It would be nice if these images can be pulled from a private registry.

**Comment by eselvam** [comment] 2022-07-22 10:05
Thanks.  Now it works fine.  Thanks for the info.

    On Friday, July 22, 2022 at 01:51:16 PM GMT+5:30, Marcel de Koster ***@***.***> wrote:  
 
 


Hi,

I seems the operator creates the trident-csi deployment that contains the following images:

k8s.gcr.io/sig-storage/csi-attacher
k8s.gcr.io/sig-storage/csi-provisioner
k8s.gcr.io/sig-storage/csi-resizer
k8s.gcr.io/sig-storage/csi-snapshotter

In an air gapped cluster the k8s.gcr.io repository cannot be reached. It would be nice if these images can be pulled from a private registry.

**Comment by gnarl** [comment] 2022-07-25 20:14
Closing this issue as air gapped installs work with Trident as long as container images are available from a private registry. A list of the required images can be found in the [Trident Requirements documentation](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html) or by running the `tridentctl images` command.

**Closed by gnarl** 2022-07-25 20:14 UTC
Labels: enhancement
