### ISSUE TITLE
CUSTOMER ISSUE - AZURE TICKET -2108040040004934

### ISSUE THREAD

**Issue by lmcdasm** [NetApp/trident#614] opened 2021-08-04 20:25 UTC
**Describe the bug**
FROM THE AZURE SUPPORT TICKET THAT WAS CREATED
\
Question: When did the problem start?
Answer: Wed, Aug 4, 2021, 12:00 AM EDT

Question: What is the new size of the volume (GiB)
Answer: 13TB

Question: Provide any additional details
Answer: We are using K8s trident driver and we want to understand how the 'resize' funciton for a given PVC is used.

For example

We have a CAP Pool that is set to 15TB
We create two volumes out of this.

VOL-A is 12TB
VOL-B is 3TB

Our goal is to increase VOL-A top 13TB.

We did (actions)
- increase the size of the capacity pool (resize)
- increased the size of the Volume (via portal)__ to 13,312 GB (13tB)

We expect:
- to see the updated volume size in the K8s cluster.

OR

- we should be able to expand the PV and PVC WITHOUT losing any data / having to copy off to a newer/expanded volume.

Question: Error message
Answer: no error message

**Environment**
Please see the Azure ticket for information.

- Trident version: [e.g. 19.10]
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: [e.g. 1.15.1]
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [e.g. RHEL 7.6, Ubuntu 16.04]
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
- Other:

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by gnarl** [comment] 2021-08-04 20:41
Hi @lmcdasm,

You should use the [volume expansion capabilities](https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/operations/tasks/volumes/vol-expansion.html) that are provided by Kubernetes. From your above description you expanded the volume by using the Azure portal instead of using the Kubernetes capabilities.

**Comment by gnarl** [comment] 2021-08-09 14:47
Hi @lmcdasm,

Were you able to resolve your issue?

**Comment by gnarl** [comment] 2021-08-16 14:19
Closing this issue as resolved. If the issue isn't resolved please comment here to have the issue reopened.

**Closed by gnarl** 2021-08-16 14:19 UTC
Labels: bug
