### ISSUE TITLE
Possibility to create a backend with a custom resource instead tridentctl.

### ISSUE THREAD

**Issue by ykoer** [NetApp/trident#538] opened 2021-02-25 15:22 UTC
We are managing our Kubernetes clusters with ArgoCD. It is currently installing the Trident Operator, but backends can be managed only with tridentctl. I would like to have the possibility to create backends with a custom resource. 
Is that feature already on your radar?

Thanks
Yusuf

**Comment by clintonk** [comment] 2021-02-25 15:28
@ykoer Yes.  @gnarl may be able to provide more insight on when you might see that.

**Comment by gnarl** [comment] 2021-03-08 17:39
Hi @ykoer,

Closing this issue as a duplicate of GitHub Issue #358. We are working on providing this support in a future Trident release.

**Closed by gnarl** 2021-03-08 17:39 UTC
Labels: enhancement

**Comment by c4m4** [comment] 2023-03-22 01:36
This is an example about how to create the backend, using the crd:

apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-btc-solidfire
  namespace: trident
type: Opaque
spec:
  version: 1
  storageDriverName: solidfire-san
  credentials:
    name: backend-btc-solidfire
  SVIP: x.x.x.x:3260
  TenantName: K8S-LAB
  Types:
    - Type: btc
      Qos:
        minIOPS: 1000
        maxIOPS: 2000
        burstIOPS: 4000
    - Type: ada
      Qos:
        minIOPS: 1000
        maxIOPS: 3000
        burstIOPS: 5000
  storage:
  storage:
    - labels:
        performance: btc
      type: btc
    - labels:
        performance: ada
      type: ada
