### ISSUE TITLE
kubernetes storage class

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#429] opened 2020-08-05 21:11 UTC
Hi

I am using kubernetes federation (federated control plane ) on 2 clusters with trident as a storage class on-prem. both are working with storage class, persistency volumes.

So, i would like to test with Federated storage class and federaeted. persistence volume to make sure the replication of volume get replicated on federation master to slave . Does this feature tested with TRident .

here is the link below , from Trident i dont see any documentation using federated storage class, federated persistence volumes. can guys check and help.

kubernetes-sigs/kubefed#1165

**Comment by gnarl** [comment] 2020-08-05 21:40
Hi @rushins,

This is an enhancement request and a duplicate of [#428 ](https://github.com/NetApp/trident/issues/428).

**Closed by gnarl** 2020-08-05 21:40 UTC
Labels: bug
