### ISSUE TITLE
Trident Container images available from more locations than DockerHub

### ISSUE THREAD

**Issue by wlgough** [NetApp/trident#653] opened 2021-09-30 19:33 UTC
**Describe the solution you'd like**
Trident Container images available from more locations than DockerHub

**Describe alternatives you've considered**
Not all customers want to pay for a corporate DockerHub subscription.

**Additional context**
Last night I scaled up the number of compute nodes in one of BCNC’s OpenShift clusters from 20 nodes to 25 nodes. This was done to create some extra compute capacity for newly installed applications running in the cluster.  The process of adding 5 compute nodes is this one-line command:
                oc -n openshift-machine-api scale machineset ocpat-f2r44-worker --replicas=25

Within about 5 minutes, the five new nodes were created and added to the cluster … but I can’t use them yet because their trident pods are stuck in ImagePullBackOff with this error message:
                11m         Warning   Failed      pod/trident-csi-lw82g        Failed to pull image "netapp/trident:20.10.0": rpc error: code = Unknown desc = Error reading manifest 20.10.0 in docker.io/netapp/trident: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Any application pods that are assigned to the new nodes would not be able to use trident to connect to storage. As a result, I’m forced to leave them in a SchedulingDisabled state until the trident pods come up. The new nodes can’t be used yet, and I don’t have the compute capacity in the cluster that I want. 

After 12 hours, the trident pods on the new nodes are still not up. I was hopeful that developer usage of Docker Hub would decrease enough overnight that the pull rate limit would be removed and the trident pods could pull their images … but this didn’t occur.

My only solution appears to be to pay for a corporate DockerHub subscription, and to configure that subscription on every BCNC OpenShift cluster. We are working on this. However, the sooner that NetApp can stop providing Trident images through DockerHub, the better.

**Comment by gnarl** [comment] 2021-09-30 20:31
We are working with NetApp IT on a solution for this issue. Closing this as a duplicate of GitHub Issue #515.

**Closed by gnarl** 2021-09-30 20:31 UTC
Labels: enhancement
