### ISSUE TITLE
solidfire-san driver could handle TenantName better (or use TenantID)

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#416] opened 2020-06-24 12:01 UTC
**Describe the bug**

ElementSW identifies storage accounts by accountID (int) and Trident uses TenantName (string) that's a mandatory to provide when a storage account ID is set up.

Problem arises when the Trident account is re-created. Technically, Trident configuration file is still correct, but Trident fails to work (not silently, but it's not easy to figure out why, because visual inspection reveals that configuration is correct).

**Environment**

* Trident version: v20.04
* Trident installation flags used: identical to SolidFire example in Trident docs for Docker
* Container runtime: Docker version 19.03.12, build 48a66213fe
* OS: Ubuntu 18.04
* NetApp backend types: Element Software 11.7

**To Reproduce**

* Setup Trident with Element v11 or newer
* Delete Tenant from Element, then create it again (obviusly Account ID will be different)
* Try to use Trident

```
$ sudo docker volume create -d netapp --name thebug -o size=1200M
Error response from daemon: create thebug: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume thebug on storage pool Bronze from backend solidfire_192.168.103.30: device reported API error], [Failed to create volume thebug on storage pool Silver from backend solidfire_192.168.103.30: device reported API error], [Failed to create volume thebug on storage pool Gold from backend solidfire_192.168.103.30: device reported API error]
```

**Expected behavior**

* Trident periodically refreshes account ID and starts using it (it'd be up to the user to not abuse the feature), - OR - 
* Trident uses TenantID, rather than TenantName

**Additional context**

A workaround is almost [documented](https://netapp-trident.readthedocs.io/en/stable-v20.04/docker/install/ndvp_sf_config.html#example-solidfire-config-file) but for a slightly different problem (deploying Trident without a storage account). Maybe we could expand on that, or add another note (for this case) to say that the recommended approach for an already deployed Trident plugin would be to run `plugin disable` and `plugin enable` if the account must be recreated. Not sure if the same would make sense in K8s.

**Comment by balaramesh** [comment] 2021-03-11 15:49
@scaleoutsean the deletion of the Tenant from ElementOS would only succeed if:

1. There are no volumes associated with the tenant. If any volume that was previously created by Trident is present, the Tenant can't be deleted unless the volumes are first deleted and purged.
2. For deleted volumes, they will need to be purged. No volume can be bound to the tenant.

It is safe to say this scenario can be experienced only when a backend is being created for the first time, or if there are no volumes created by Trident yet, or if all previously created volumes have been deleted.

Secondly, if the tenant is deleted and recreated (a scenario where the accountID would change), or if a new tenant (one with a different name is created), the course of operations will be:

1. Create/update an existing Trident backend (`tridentctl update backend <backend-name> -f backend.json -n trident`)

Trident will then pick up the new accountID and volumes can be created successfully.

**Comment by scaleoutsean** [comment] 2021-03-11 16:32
I agree, those are all unlikely to happen in real environments so I don't have a strong opinion on how to deal with it - maybe just add a note somewhere in the unlikely case someone runs into this? 
Although they might find it in this Trident issue as well, which is one of reasons I created it - we could also just close this - anyone who checks Issues should be able to figure it out. I wouldn't have reported it if the error (`device reported API error`) didn't take me down the wrong path (troubleshooting iscsi.conf and other unrelated parts) - hopefully others can quickly find this issue and save troubleshooting time.

**Comment by gnarl** [comment] 2021-03-15 14:41
Closing this issue as recommended by @scaleoutsean. The issue is documented here in the unlikely event that a customer experiences this issue.

**Closed by gnarl** 2021-03-15 14:41 UTC
Labels: bug, solidfire, tracked
