### ISSUE TITLE
Trident bug in provisioning with Kubernetes.

### ISSUE THREAD

**Issue by dsmithfv** [NetApp/trident#133] opened 2018-06-15 16:10 UTC
As documented in: https://github.com/NetApp/trident/issues/101

"The iSCSI driver doesn't delete a device upon detach as there is no rescan following unmount."

Looking at K8s documentation I noticed Trident is failing to set the portals setting for LUNS.  We performed testing and found that setting the portals resolves this issue.  Below is a snippet of our pv configuration.

```
iscsi:
  fsType: ext4
  iqn: iqn.1992-08.com.netapp:sn.12345678910:vs.4
  iscsiInterface: default
  lun: 6
  targetPortal: 10.28.52.128
  portals:
  - 10.28.52.128
  - 10.28.52.129
  - 10.28.52.130
  - 10.28.52.131
  - 10.28.52.136
  - 10.28.52.137
  - 10.28.52.138
  - 10.28.52.139
```

After manually creating a pv and pvc connected to the Ontap the ISCSI device was removed as expected.
Using Trident to dynamically provision it did not. Is it possible to update Trident to add the additional paths to the portal section above?

**Comment by innergy** [comment] 2018-07-19 01:40
@bswartz Is this a combination of the upstream Kubernetes fix you have in flight and support for multiple target portals in Trident?

**Comment by bswartz** [comment] 2018-07-21 00:32
This bug will be fixed by my currently open Trident PR.

There are 2 other Kubernetes fixes related to iSCSI and multipathing, but not needed to solve this issue.

**Comment by adkerr** [comment] 2018-08-08 22:06
@dondsmithtx if this is a duplicate of #69, which it appears to be, then yes it is in 18.07.0.

**Comment by bswartz** [comment] 2018-09-20 20:26
This is fixed by https://github.com/NetApp/trident/commit/0c235c12f64ca3d7736f35a6b49d85eb0915e94d and https://github.com/kubernetes/kubernetes/commit/845a55dbbda9a35cfd3659f1fe880d35a03dc44b

**Closed by bswartz** 2018-09-20 20:26 UTC
Labels: bug, eseries, kubernetes, ontap-san, solidfire, tracked
