### ISSUE TITLE
Support running tridentctl from a pod

### ISSUE THREAD

**Issue by canhnt** [NetApp/trident#202] opened 2019-01-04 11:33 UTC
When installing trident-v18.10.0 using tridentctl-v18.10.0, if I run the command:
```
./tridentctl install -n trident -d
```

The result is:
```
DEBU Initialized logging.                          logLevel=debug
DEBU Running in a pod, creating API-based client.  namespace=trident
DEBU Initialized Kubernetes API client.            cli=kubectl flavor=k8s namespace=trident version=v1.12.3
DEBU Validated installation environment.           installationNamespace=trident kubernetesVersion=v1.12.3
DEBU Namespace exists.                             namespace=trident
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRoleBinding version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRoleBinding resource=clusterrolebindings version=v1
DEBU Deleting object.                              kind=ClusterRoleBinding name=trident-installer namespace=trident
DEBU Object not found for delete, ignoring.        name=trident-installer
DEBU Deleted installer cluster role binding.
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRole version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRole resource=clusterroles version=v1
DEBU Deleting object.                              kind=ClusterRole name=trident-installer namespace=trident
DEBU Object not found for delete, ignoring.        name=trident-installer
DEBU Deleted installer cluster role.
DEBU Parsed YAML into unstructured object.         group= kind=ServiceAccount version=v1
DEBU Found API resource.                           group= kind=ServiceAccount resource=serviceaccounts version=v1
DEBU Deleting object.                              kind=ServiceAccount name=trident-installer namespace=trident
DEBU Object not found for delete, ignoring.        name=trident-installer
DEBU Deleted installer service account.
DEBU Parsed YAML into unstructured object.         group= kind=ServiceAccount version=v1
DEBU Found API resource.                           group= kind=ServiceAccount resource=serviceaccounts version=v1
DEBU Creating object.                              kind=ServiceAccount name=trident-installer namespace=trident
DEBU Created object by YAML.                       name=trident-installer
INFO Created installer service account.            serviceaccount=trident-installer
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRole version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRole resource=clusterroles version=v1
DEBU Creating object.                              kind=ClusterRole name=trident-installer namespace=trident
DEBU Created object by YAML.                       name=trident-installer
INFO Created installer cluster role.               clusterrole=trident-installer
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRoleBinding version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRoleBinding resource=clusterrolebindings version=v1
DEBU Creating object.                              kind=ClusterRoleBinding name=trident-installer namespace=trident
DEBU Created object by YAML.                       name=trident-installer
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRoleBinding version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRoleBinding resource=clusterrolebindings version=v1
DEBU Deleting object.                              kind=ClusterRoleBinding name=trident-installer namespace=trident
DEBU Deleted object by YAML.                       name=trident-installer
INFO Deleted installer cluster role binding.
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRole version=v1
DEBU Found API resource.                           group=rbac.authorization.k8s.io kind=ClusterRole resource=clusterroles version=v1
DEBU Deleting object.                              kind=ClusterRole name=trident-installer namespace=trident
DEBU Deleted object by YAML.                       name=trident-installer
INFO Deleted installer cluster role.
DEBU Parsed YAML into unstructured object.         group= kind=ServiceAccount version=v1
DEBU Found API resource.                           group= kind=ServiceAccount resource=serviceaccounts version=v1
DEBU Deleting object.                              kind=ServiceAccount name=trident-installer namespace=trident
DEBU Deleted object by YAML.                       name=trident-installer
INFO Deleted installer service account.
FATA Install failed; not implemented.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.
```

Fix: I have to run `./tridentctl install -n trident -d --in-cluster=false`, then it's successful.

Investigation: into the code, the `in-cluster` arg default value in v18.07 is `false`: https://github.com/NetApp/trident/blob/stable/v18.07/cli/cmd/install.go#L117. While in v18.10, the default is `true`. Then the install code runs `CreateConfigMapFromDirectory` that was not implemented:
https://github.com/NetApp/trident/blob/stable/v18.10/cli/k8s_client/k8s_client.go#L672

**Comment by innergy** [comment] 2019-03-14 16:32
We've been unable to reproduce this. The default is intentionally the in-cluster method, and we have not had any other reports of this failing. Please try again with the latest stable version. If you still see this issue, feel free to re-open with more information about your environment, logs, etc.

**Comment by canhnt** [comment] 2019-03-14 16:49
The reproduction path requires following:
 - Install trident as a pod: then a new KubeClient is created: https://github.com/NetApp/trident/blob/47c001ba9ecfa9b8de0a4bd1e1e5dafc0ccbd6ad/cli/cmd/install.go#L262 
- Run with default `in-cluster=true`, then the method `CreateConfigMapFromDirectory` is called at https://github.com/NetApp/trident/blob/47c001ba9ecfa9b8de0a4bd1e1e5dafc0ccbd6ad/cli/cmd/install.go#L1622, this method is not implemented and return Error object.

**Comment by innergy** [comment] 2019-03-14 17:35
@clintonk, can you explain how someone would fall into this situation?

Installation as a pod (in-cluster=true) is the default installation method, so there must be something else going on. If there were some basic issue like this, installations to be failing all the time.

Have you tried with 19.01?

**Comment by clintonk** [comment] 2019-03-14 17:55
@innergy I'm assuming that ```./tridentctl install -n trident -d``` is being run directly on a host and is not somehow being wrapped in a K8S pod.  If that assumption is true, the only way I can see that we'd get here is if the file ```/var/run/secrets/kubernetes.io/serviceaccount/namespace``` exists on the host.  Reading that file is how we determine whether or not we are running in a K8S container; it should exist inside a K8S pod and it should not exist outside a pod.

**Comment by canhnt** [comment] 2019-03-14 21:28
We're running tridentctl inside a pod (of a Docker image containing all trident-installer and kubectl tools). That explains why the execution flow goes through that branch.

**Comment by clintonk** [comment] 2019-03-14 21:34
@canhnt Yes, that explains it.  Since you're already inside a pod, the workaround is to use ```--in-cluster=false```.  Keep in mind we haven't ever tested the installer that way, but it seems to me it should work.

**Comment by shamziman** [comment] 2019-07-15 10:42
tridentctl can already be run in the shell in the running trident container and corresponding namespace. I think what you are asking for is installing trident from/within a container/pod

**Comment by gnarl** [comment] 2020-10-25 21:17
Closing this issue as workaround solutions were provided.

**Closed by gnarl** 2020-10-25 21:17 UTC
Labels: enhancement, tracked
