### ISSUE TITLE
Trident 19.10 expanding NFS size mounted within the Kubernetes pod

### ISSUE THREAD

**Issue by Swetad90** [NetApp/trident#422] opened 2020-07-23 16:21 UTC
**Describe the bug**
Trident is being used to procure persistent volume for Prometheus. The Persistent volume size is requested to be 70GB.
The PV size in kuberenetes & volume size in trident confirms the same:

`   kubectl get pv -n metrics`
    
    NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                             STORAGECLASS   REASON   AGE
    pvc-7225442a-2d68-4645-9a65-bdf16f4172ea   70Gi       RWO            Delete           Bound      metrics/prometheus-prometheus-0   ontapnas                195d
    pvc-f49a1b75-44e3-4d02-a091-0de4486daace   70Gi       RWO            Delete           Bound      metrics/prometheus-prometheus-1   ontapnas                195d`

`trident-19_10$ ./tridentctl get volumes -n trident`

    +------------------------------------------+---------+---------------+----------+--------------------------------------+--------+---------+
    |                   NAME                   |  SIZE   | STORAGE CLASS | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
    +------------------------------------------+---------+---------------+----------+--------------------------------------+--------+---------+

    | pvc-7225442a-2d68-4645-9a65-bdf16f4172ea | 70 GiB  | ontapnas      | file     | acf02a4a-9dc7-4f8b-ad81-5ba5daef8ed0 | online | true    |
    | pvc-f49a1b75-44e3-4d02-a091-0de4486daace | 70 GiB  | ontapnas      | file     | acf02a4a-9dc7-4f8b-ad81-5ba5daef8ed0 | online | true    |

But when I exec into the pod to check the size of the data, the mounted volume is of 114GB whereas 'du` of the same point just shows 58GB:

`kubectl exec -it prometheus-1 -n metrics -c prometheus sh`

    /prometheus $ df -h
    Filesystem                Size      Used Available Use% Mounted on
    overlay                   9.8G      6.5G      2.8G  70% /
    tmpfs                    64.0M         0     64.0M   0% /dev
    tmpfs                     7.8G         0      7.8G   0% /sys/fs/cgroup
    17x.xx.xx.xxx:/trident_test_pvc_f49a1b75_44e3_4d02_a091_0de4486daace
                        114.0G     85.5G     28.5G  75% /prometheus
    /dev/mapper/ubuntu--vg-lv--var
                          9.3G      3.4G      5.5G  38% /etc/prometheus-shared
    /dev/mapper/ubuntu--vg-lv--var
                          9.3G      3.4G      5.5G  38% /etc/prometheus/rules
    tmpfs                     7.8G     12.0K      7.8G   0% /var/run/secrets/kubernetes.io/serviceaccount

    /prometheus $ du -sh /prometheus/
    52.8G 

Here is the storage class & backend:

     allowVolumeExpansion: true
     apiVersion: storage.k8s.io/v1
     kind: StorageClass
     metadata:
       annotations:
         storageclass.kubernetes.io/is-default-class: "true"
     parameters:
     backendType: ontap-nas
     provisioner: csi.trident.netapp.io
     reclaimPolicy: Delete
     volumeBindingMode: Immediate 

    {
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "17x.xx.xx.xxx",
    "dataLIF": "17x.xx.xx.xxx",
    "svm": "testsvm",
    "username": "testuser",
    "password": "******",
    "nfsMountOptions": "nfsvers=4",
    "storagePrefix": "trident_test",
    "defaults": {
      "exportPolicy": "k8workers",
      "spaceReserve": "volume",
      "snapshotPolicy": "local_snaps",
      "snapshotDir": "true",
      "securityStyle": "unix",
      "limitVolumeSize": "100gb"
    }
  }

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [19.10]
- Trident installation flags used: [./tridentctl install -n trident --config setup/backend.json]
- Container runtime: [Docker 18.09.7-CE]
- Kubernetes version: [1.15.7]
- Kubernetes orchestrator: [Baremetal, setup using kubespray2.11]
- OS: [Ubuntu 18.04.1 LTS]
- NetApp backend types: [ONTAP NAS]

**Expected behavior**
The volume size to remain constant at 70GB and won't expand on it's own to 114GB. We have enabled allow expansion on storage class but we would want to control the size of the volume.

**Additional context**
I keep seeing this log as warnings in trident
time="2020-07-23T16:14:18Z" level=warning msg="K8S helper can't shrink a PV." PVC=prometheus-prometheus-1
time="2020-07-23T16:14:18Z" level=warning msg="K8S helper can't shrink a PV." PVC=prometheus-prometheus-1

**Comment by gnarl** [comment] 2020-07-23 16:59
Hi @Swetad90, 

Trident does not provide autogrow functionality. In order to resize a PV you have to edit the PVC and specify a new size. 

It appears that Trident is receiving a request from K8S to shrink the PV from the "K8S helper can't shrink a PV" message. Trident also doesn't support shrinking PVs. 

To be honest I'm not sure how your PV is in this situation. It could have been expanded on the backend outside of Trident but that doesn't explain why K8S thinks that the PV needs to shrink. Someone could have edited the PVC from a larger size to 70 GiB but the information you've provided doesn't agree with that. 

Can you provide the output from `kubectl describe pvc <pvc_name>` ? This may provide more information.

**Comment by Swetad90** [comment] 2020-07-23 21:24
Name:          prometheus-prometheus-1
    Namespace:     metrics
    StorageClass:  ontapnas
    Status:        Bound
    Volume:        pvc-f49a1b75-44e3-4d02-a091-0de4486daace
    Labels:        app=prometheus
    Annotations:   pv.kubernetes.io/bind-completed: yes
                          pv.kubernetes.io/bound-by-controller: yes
                         volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
    Finalizers:    [kubernetes.io/pvc-protection]
    Capacity:      70Gi
    Access Modes:  RWO
    VolumeMode:    Filesystem
    Mounted By:    prometheus-1
    Events:
       Type     Reason        Age                     From                   Message
       ----     ------        ----                    ----                   -------
      Warning  ResizeFailed  82s (x1645 over 3d10h)  csi.trident.netapp.io  can't shrink a PV.

We do have auto-expansion enabled but haven't edited the PV to resize the volume at all in this cluster yet. And that's what is bothering me as to why is the volume auto expanding. 

I could confirm even on the NetApp end the volume `17x.xx.xx.xxx:/trident_test_pvc_f49a1b75_44e3_4d02_a091_0de4486daace` has AutoGrow disabled.

**Comment by gnarl** [comment] 2020-08-11 20:11
@Swetad90, did you ever determine the cause of this issue?

**Comment by Swetad90** [comment] 2020-12-01 20:55
@gnarl yes, we figured the below to be the cause:
Trident allows us to procure volumes by "thick" or "thin" provisioning by setting the "snapreserve" parameter in the backend config to "volume" or "none" respectively. When set to "volume", the entire PV size is thick provisioned, and hence, snapshots are taken of the volume as a whole. When this happens, snapshots generally grows outside of its reserved space ie 5%, and grows into the userspace. As a result, we see the 114GB of the mount size which included just 50GB of user data and rest being the snapshots.

**Comment by gnarl** [comment] 2021-01-25 15:26
Closing this as a duplicate of  an [enhancement request](https://github.com/NetApp/trident/issues/496) that is being tracked.

**Closed by gnarl** 2021-01-25 15:26 UTC
Labels: bug
